### ISSUE TITLE
Ship app logs with Filebeat to complete the Metrics, Logs, Traces holy trinity of observability

### ISSUE THREAD

**Issue by chuck-confluent** [riferrei/otel-with-java#3]
Just a thought!

**Comment by riferrei** [comment]
While I fancy the idea of completing the trinity, this repo is all about OTel, and unfortunately, is not yet supported in OTel.

But if you need an example that integrates everything using Elastic — this repo might help: https://github.com/riferrei/from-zero-to-hero-with-observability
